defaults: &DEFAULTS
  server_path: "https://s3-us-west-2.amazonaws.com/bbcirfs/coot/logs/"
  server_path_image: "https://s3-us-west-2.amazonaws.com/bbcirfs/coot/testing/"

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS